# Generated by Django 6.0.6 on 2026-09-06 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='photo',
        ),
    ]
