# Generated by Django 6.0.6 on 2026-07-27 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Кличка')),
                ('type', models.CharField(choices=[('cat', 'кошка'), ('dog', 'собака')], max_length=3, verbose_name='Вид')),
                ('breed', models.CharField(max_length=60, verbose_name='Порода')),
                ('gender', models.CharField(choices=[('F', 'женский'), ('M', 'мужской')], max_length=1, verbose_name='Пол')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('birth_date', models.DateField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='clients.client', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
            },
        ),
    ]
