# Generated by Django 6.0.6 on 2026-09-10 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_remove_client_photo'),
        ('doctors', '0002_doctor_photo'),
        ('pets', '0002_alter_pet_birth_date_alter_pet_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Ожидается'), ('completed', 'Завершен'), ('canceled', 'Отменен'), ('no_show', 'Пациент не явился')], default='scheduled', max_length=20, verbose_name='Статус визита')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bookings', to='clients.client', verbose_name='Клиент')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_bookings', to='pets.pet', verbose_name='Питомец')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.TextField(default='Плановый осмотр', verbose_name='Жалобы')),
                ('diagnosis', models.TextField(default='Здоровье впорядке', verbose_name='Диагноз')),
                ('prescription', models.TextField(null=True, verbose_name='Назначения')),
                ('next_visit', models.CharField(default='Не требуется', max_length=250, verbose_name='Повторный прием')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='pets.pet', verbose_name='Питомец')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='receptions.booking', verbose_name='Визит')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата приема')),
                ('start', models.TimeField(verbose_name='Начало приема')),
                ('end', models.TimeField(verbose_name='Окончание приема')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступность для записи')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_slots', to='doctors.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Окно приема',
                'verbose_name_plural': 'Окна приема',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptions.workingslot', verbose_name='Визит'),
        ),
    ]
