# Generated by Django 6.0.5 on 2026-06-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0003_servicecategory_service_comment_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
