# Generated by Django 6.0.5 on 2026-06-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0004_alter_service_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
