# Generated by Django 6.0.6 on 2026-09-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0006_alter_service_options_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Категория'),
        ),
    ]
